=== xXxEdyxXx/F1-XML/SchemaF1.xsd
<xs:schema elementFormDefault="qualified" targetNamespace="http://FormulaTeamsStua05.com/F1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="F1" type="f1:F1Type" xmlns:f1="http://FormulaTeamsStua05.com/F1">
        <xs:key name="DriverNumberKey">
            <xs:selector xpath="f1:Team/f1:Drivers/f1:Driver"/>
            <xs:field xpath="f1:DriverNumber"/>
        </xs:key>
        
        <xs:keyref name="DriverNumberRef" refer="f1:DriverNumberKey">
            <xs:selector xpath="f1:Team/f1:Drivers/f1:Driver"/>
            <xs:field xpath="f1:DriverNumber"/>
        </xs:keyref>
    </xs:element>


    <xs:complexType name="F1Type">
        <xs:sequence>
            <xs:element type="f1:TeamType" name="Team" maxOccurs="unbounded" minOccurs="0"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TeamType">
        <xs:sequence>
            <xs:element type="f1:TeamNameType" name="TeamName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:anyURI" name="Logo"/>
            <xs:element type="f1:DriversType" name="Drivers"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:CarsType" name="Cars" xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:TeamBaseType" name="TeamBase"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:TeamPrincipalType" name="TeamPrincipal"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:TechnicalDirectorType" name="TechnicalDirector"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:string" name="MainSponsor" default="None"/>
            <xs:element type="xs:short" name="Founded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TeamNameType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="ConstructorChampionsWon" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="DriversType">
        <xs:sequence>
            <xs:element type="f1:DriverType" name="Driver" maxOccurs="unbounded" minOccurs="0"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"> </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DriverType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="f1:FirstNameType" name="FirstName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:string" name="MiddleName"/>
            <xs:element type="f1:NotEmptyString" name="LastName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:NotEmptyString" name="Nationality"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:DriverNumberType" name="DriverNumber"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:nonNegativeInteger" name="RaceWins"/>
            <xs:element type="xs:nonNegativeInteger" name="RaceEntries"/>
            <xs:element type="f1:PointsType" name="Points"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:nonNegativeInteger" name="Podiums"/>
            <xs:element type="xs:nonNegativeInteger" name="PolePositions"/>
            <xs:element type="xs:nonNegativeInteger" name="FastestLaps"/>
            <xs:element type="f1:DateOfBirthType" name="DateOfBirth"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
        </xs:choice>
        <xs:attribute type="xs:nonNegativeInteger" name="ChampionshipsWon" use="optional"/>
    </xs:complexType>

    <xs:complexType name="FirstNameType">
        <xs:simpleContent>
            <xs:extension base="f1:NotEmptyString" xmlns:f1="http://FormulaTeamsStua05.com/F1">
                <xs:attribute type="xs:string" name="Title" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="NotEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DriverNumberType">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="99"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PointsType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DateOfBirthType">
        <xs:restriction base="xs:string">
            <xs:pattern value="1[0-9]{3}|20[0-2][0-4]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CarsType">
        <xs:sequence>
            <xs:element type="xs:string" name="CarModel"/>
            <xs:element type="xs:string" name="Livery"/>
            <xs:element type="f1:EngineSupplierType" name="EngineSupplier" minOccurs="0"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TeamBaseType">
        <xs:sequence>
            <xs:element type="f1:CountryType" name="Country"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:string" name="City"/>
            <xs:element type="xs:string" name="Street"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="CountryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Italy"/>
            <xs:enumeration value="United Kingdom"/>
            <xs:enumeration value="Switzerland"/>
            <xs:enumeration value="USA"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EngineSupplierType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Honda"/>
            <xs:enumeration value="Mercedes"/>
            <xs:enumeration value="Ferrari"/>
            <xs:enumeration value="Renault"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TeamPrincipalType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="f1:FirstNameType" name="FirstName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:NotEmptyString" name="LastName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:string" name="MiddleName"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="Title" use="optional"/>
    </xs:complexType>

    <xs:complexType name="TechnicalDirectorType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="f1:FirstNameType" name="FirstName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="f1:NotEmptyString" name="LastName"
                xmlns:f1="http://FormulaTeamsStua05.com/F1"/>
            <xs:element type="xs:string" name="MiddleName"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="Title" use="optional"/>
    </xs:complexType>




</xs:schema>

=== xXxEdyxXx/F1-XML/DokumentF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="SchematronF1.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<F1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://FormulaTeamsStua05.com/F1 SchemaF1.xsd"
 xmlns="http://FormulaTeamsStua05.com/F1">
    


        <Team>
            <TeamName ConstructorChampionsWon="6">Red Bull Racing</TeamName>
            <Logo>Loga/RedBullRacing.png</Logo>
            <Drivers>
                <Driver ChampionshipsWon="3">
                    <FirstName>Max</FirstName>
                    <MiddleName>Emilian</MiddleName>
                    <LastName>Verstappen</LastName>
                    <Nationality>Dutch</Nationality>
                    <DriverNumber>1</DriverNumber>
                    <RaceWins>54</RaceWins>
                    <RaceEntries>185</RaceEntries>
                    <Points>2586.5</Points>
                    <Podiums>98</Podiums>
                    <PolePositions>32</PolePositions>
                    <FastestLaps>30</FastestLaps>
                    <DateOfBirth>1998</DateOfBirth>
                </Driver>
                <Driver>
                    <FirstName>Sergio</FirstName>
                    <MiddleName>Michel Mendoza</MiddleName>
                    <LastName>Perez</LastName>
                    <Nationality>Mexican</Nationality>
                    <DriverNumber>11</DriverNumber>
                    <RaceWins>6</RaceWins>
                    <RaceEntries>261</RaceEntries>
                    <Points>1486</Points>
                    <Podiums>32</Podiums>
                    <PolePositions>3</PolePositions>
                    <FastestLaps>11</FastestLaps>
                    <DateOfBirth>1991</DateOfBirth>
                </Driver>
            </Drivers>
            <Cars>
                <CarModel>Red Bull Racing RB19</CarModel>
                <Livery>Red Bull Blue</Livery>
                <EngineSupplier>Honda</EngineSupplier>
            </Cars>
            <TeamBase>
                <Country>United Kingdom</Country>
                <City>Milton Keynes</City>
                <Street>Bradbourne Drive</Street>
            </TeamBase>
            <TeamPrincipal Title="OBE">
                <FirstName>Christian</FirstName>
                <LastName>Horner</LastName>
                <MiddleName>Edward Johnston</MiddleName>
            </TeamPrincipal>
            <TechnicalDirector Title="OBE">
                <FirstName>Adrian</FirstName>
                <LastName>Newey</LastName>
                <MiddleName>Martin</MiddleName>
            </TechnicalDirector>
            <MainSponsor>Oracle</MainSponsor>
            <Founded>2005</Founded>
        </Team>

        <Team>
            <TeamName ConstructorChampionsWon="8">Mercedes-AMG Petronas Formula One Team</TeamName>
            <Logo>Loga/Mercedes-AMGPetronasFormulaOneTeam.png</Logo>
            <Drivers>
                <Driver ChampionshipsWon="7">
                    <FirstName Title="Sir">Lewis</FirstName>
                    <MiddleName>Carl</MiddleName>
                    <LastName>Hamilton</LastName>
                    <Nationality>British</Nationality>
                    <DriverNumber>44</DriverNumber>
                    <RaceWins>103</RaceWins>
                    <RaceEntries>275</RaceEntries>
                    <Points>4361.5</Points>
                    <Podiums>178</Podiums>
                    <PolePositions>103</PolePositions>
                    <FastestLaps>53</FastestLaps>
                    <DateOfBirth>1987</DateOfBirth>
                </Driver>
                <Driver>
                    <FirstName>George</FirstName>
                    <MiddleName>William</MiddleName>
                    <LastName>Russel</LastName>
                    <Nationality>British</Nationality>
                    <DriverNumber>63</DriverNumber>
                    <RaceWins>1</RaceWins>
                    <RaceEntries>59</RaceEntries>
                    <Points>43</Points>
                    <Podiums>11</Podiums>
                    <PolePositions>1</PolePositions>
                    <FastestLaps>6</FastestLaps>
                    <DateOfBirth>2000</DateOfBirth>
                </Driver>
            </Drivers>
            <Cars>
                <CarModel>Mercedes-AMG F1 W14 E Performance</CarModel>
                <Livery>Black</Livery>
                <EngineSupplier>Mercedes</EngineSupplier>
            </Cars>
            <TeamBase>
                <Country>United Kingdom</Country>
                <City>Brackley</City>
                <Street>Lauda Drive</Street>
            </TeamBase>
            <TeamPrincipal>
                <FirstName>Toto</FirstName>
                <LastName>Wolff</LastName>
                <MiddleName>Christian</MiddleName>
            </TeamPrincipal>
            <TechnicalDirector>
                <FirstName>James</FirstName>
                <LastName>Allison</LastName>
                <MiddleName>Andrew</MiddleName>
            </TechnicalDirector>
            <MainSponsor>Petronas</MainSponsor>
            <Founded>2010</Founded>
        </Team>

        <Team>
            <TeamName>Scuderia Ferrari</TeamName>
            <Logo>Loga/ScuderiaFerrari.png</Logo>
            <Drivers>
                <Driver>
                    <FirstName>Charles</FirstName>
                    <MiddleName>Percival</MiddleName>
                    <LastName>Leclerc</LastName>
                    <Nationality>Monegasque</Nationality>
                    <DriverNumber>16</DriverNumber>
                    <RaceWins>5</RaceWins>
                    <RaceEntries>125</RaceEntries>
                    <Points>1074</Points>
                    <Podiums>30</Podiums>
                    <PolePositions>15</PolePositions>
                    <FastestLaps>13</FastestLaps>
                    <DateOfBirth>1998</DateOfBirth>
                </Driver>
                <Driver>
                    <FirstName>Carlos</FirstName>
                    <MiddleName>Vázquez de Castro</MiddleName>
                    <LastName>Sainz</LastName>
                    <Nationality>Spanish</Nationality>
                    <DriverNumber>55</DriverNumber>
                    <RaceWins>2</RaceWins>
                    <RaceEntries>185</RaceEntries>
                    <Points>982.5</Points>
                    <Podiums>18</Podiums>
                    <PolePositions>3</PolePositions>
                    <FastestLaps>2</FastestLaps>
                    <DateOfBirth>1995</DateOfBirth>
                </Driver>
            </Drivers>
            <Cars>
                <CarModel>Ferrari SF-21</CarModel>
                <Livery>Red</Livery>
                <EngineSupplier>Ferrari</EngineSupplier>
            </Cars>
            <TeamBase>
                <Country>Italy</Country>
                <City>Maranello</City>
                <Street>Pastarino</Street>
            </TeamBase>
            <TeamPrincipal>
                <FirstName>Frederic</FirstName>
                <MiddleName>Bino</MiddleName>
                <LastName>Vasser</LastName>
            </TeamPrincipal>
            <TechnicalDirector>
                <FirstName>Enrico</FirstName>
                <MiddleName>Jack</MiddleName>
                <LastName>Galletti</LastName>
            </TechnicalDirector>
            <MainSponsor>Mission Winnow</MainSponsor>
            <Founded>1929</Founded>
        </Team>

        <Team>
            <TeamName ConstructorChampionsWon="2">Alpine F1 Team</TeamName>
            <Logo>Loga/AlpineF1Team.png</Logo>
            <Drivers>
                <Driver>
                    <FirstName>Esteban</FirstName>
                    <LastName>Ocon</LastName>
                    <MiddleName>José Jean-Pierre</MiddleName>
                    <Nationality>French</Nationality>
                    <DriverNumber>31</DriverNumber>
                    <RaceWins>1</RaceWins>
                    <RaceEntries>133</RaceEntries>
                    <Points>422</Points>
                    <Podiums>3</Podiums>
                    <PolePositions>0</PolePositions>
                    <FastestLaps>1</FastestLaps>
                    <DateOfBirth>1999</DateOfBirth>
                </Driver>
                <Driver>
                    <FirstName>Piere</FirstName>
                    <LastName>Gasly</LastName>
                    <MiddleName>Jean-Jacques</MiddleName>
                    <Nationality>French</Nationality>
                    <DriverNumber>10</DriverNumber>
                    <RaceWins>1</RaceWins>
                    <RaceEntries>130</RaceEntries>
                    <Points>218</Points>
                    <Podiums>2</Podiums>
                    <PolePositions>1</PolePositions>
                    <FastestLaps>2</FastestLaps>
                    <DateOfBirth>1998</DateOfBirth>
                </Driver>
            </Drivers>
            <Cars>
                <CarModel>Alpine A523</CarModel>
                <Livery>Blue</Livery>
                <EngineSupplier>Renault</EngineSupplier>
            </Cars>
            <TeamBase>
                <Country>United Kingdom</Country>
                <City>Enstone</City>
                <Street>Chipin Norton</Street>
            </TeamBase>
            <TeamPrincipal>
                <FirstName>Bruno</FirstName>
                <LastName>Famin</LastName>
                <MiddleName>Lucien</MiddleName>
            </TeamPrincipal>
            <TechnicalDirector>
                <FirstName>Eric</FirstName>
                <LastName>Meignan</LastName>
                <MiddleName>Charles</MiddleName>
            </TechnicalDirector>
            <MainSponsor>BWT</MainSponsor>
            <Founded>2021</Founded>
        </Team>

        <Team>
            <TeamName ConstructorChampionsWon="8">McLaren F1 Team</TeamName>
            <Logo>Loga/McLarenF1Team.png</Logo>
            <Drivers>
